// Mocks generated by Mockito 5.0.3 from annotations
// in arbify/test/arbify_api_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;
import 'dart:typed_data' as _i5;

import 'package:dio/src/adapter.dart' as _i2;
import 'package:dio/src/options.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeResponseBody extends _i1.Fake implements _i2.ResponseBody {}

/// A class which mocks [HttpClientAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClientAdapter extends _i1.Mock implements _i2.HttpClientAdapter {
  MockHttpClientAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.ResponseBody> fetch(
          _i4.RequestOptions? options,
          _i3.Stream<_i5.Uint8List>? requestStream,
          _i3.Future<dynamic>? cancelFuture) =>
      (super.noSuchMethod(
              Invocation.method(#fetch, [options, requestStream, cancelFuture]),
              returnValue: Future.value(_FakeResponseBody()))
          as _i3.Future<_i2.ResponseBody>);
  @override
  void close({bool? force = false}) =>
      super.noSuchMethod(Invocation.method(#close, [], {#force: force}),
          returnValueForMissingStub: null);
}
